[tool.poetry]
name = "pendulum-integrator"
version = "0.1.0"
description = ""
authors = ["SimonB <Simon_Baeuerle@web.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
